---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 12h
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1h
  timeout: 5m
  releaseName: argo-cd
  targetNamespace: argocd
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argocd
      interval: 1m

  # values:
  #   global: 
  #     domain: argocd.example.com

  values:
    configs:
      cm:
        accounts.developer1: apiKey,login
        accounts.developer2: apiKey,login
        accounts.operator1: apiKey,login
        accounts.readonly1: apiKey,login
        # Configuración de políticas RBAC
        policy.csv: |
          p, role:developer, clusters, get, *, allow
          p, role:developer, projects, get, *, allow
          p, role:developer, applications, get, */*, allow
          p, role:developer, applications, sync, */*, allow
          p, role:developer, applications, list, */*, allow
          p, role:developer, repositories, get, *, allow
          p, role:developer, logs, get, */*, allow
          p, role:developer, exec, create, */*, allow
          g, developer1, role:developer
          g, developer2, role:developer

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3